#!/bin/bash

# Function to display script usage
show_help() {
    echo "Usage: $0 <DOMAIN> <WORDLIST> <URL> <FS Filter> [Additional ffuf args]"
    echo "   -h, --help     Display this help and exit"
    echo
    echo "This script is a vhost fuzzer using ffuf for people who may forget the syntax."
    echo
    echo "Example:"
    echo "  $0 example.com wordlist.txt https://example.com 138"
    echo "  $0 example.com wordlist.txt https://example.com 138 '-t 100 -rate 50'"
}

# Check if the help option is provided
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    show_help
    exit 0
fi

# Check if the required arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Error: Missing or incorrect arguments."
    show_help
    exit 1
fi

# Assign arguments to variables
DOMAIN="$1"
WORDLIST="$2"
URL="$3"
FS="$4"
EXTRA_ARGS="${5:-}"

# Run ffuf command
ffuf -H "Host: FUZZ.$DOMAIN" -H "User-Agent: PENTESTING" -c -w "$WORDLIST" -u "$URL" -fs "$FS" $EXTRA_ARGS
